version: "3.8"

services:   
  server:
    build: ./
    ports:
      - 3000:3000
    environment:
      - DB_USER=
      - DB_PASSWORD=
      - JWT_SECRET=
    networks:
      - public
      
networks:
  public:
    driver: bridge